// This file is auto-generated by: pnpm db:types
// Run `pnpm db:types` after schema changes to regenerate

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      // Tables will be auto-generated after running migrations
      // See supabase/migrations/ for schema definitions
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
        Relationships: unknown[]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      attendance_status: 'present' | 'absent' | 'late' | 'half_day' | 'holiday'
      payment_mode: 'cash' | 'cheque' | 'upi' | 'neft' | 'card' | 'online'
      user_role: 'super_admin' | 'school_admin' | 'teacher' | 'manager' | 'cashier' | 'parent'
      fee_status: 'pending' | 'partial' | 'paid' | 'overdue' | 'waived'
      gender: 'male' | 'female' | 'other'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
